import LeadForm from "./lead-form";

const Check = () => <span className="check" aria-hidden="true">✓</span>;

export default function Home() {
  return (
    <main>
      <header className="nav"><a className="brand" href="#inicio"><span className="brandMark"><img src="/ciclo-mob-logo-oficial.png" alt=""/></span> Ciclo MOB</a><a className="navCta" href="#planos">Quero começar</a></header>
      <section className="hero" id="inicio">
        <div className="heroCopy"><span className="eyebrow">Autoconhecimento começa na observação</span><h1>Conheça seus ritmos. <em>Registre sua história.</em></h1><p>Transforme as percepções do seu dia em uma visão mais clara do seu ciclo, do seu corpo e das mudanças que fazem parte de você.</p><div className="heroActions"><a className="button primary" href="#planos">Conhecer o Ciclo MOB</a><a className="button ghost" href="#como-funciona">Ver como funciona</a></div><div className="trust"><span>✓ Acesso pelo celular</span><span>✓ Tema claro e escuro</span><span>✓ Registros protegidos</span></div></div>
        <div className="heroVisual"><div className="orb"/><img src="/ciclo-mob-v38-hoje.png" alt="Tela Hoje da nova versão do aplicativo Ciclo MOB"/><div className="floatCard"><b>Um momento para você</b><span>Observe, registre e compreenda.</span></div></div>
      </section>
      <section className="softSection"><div className="sectionHead"><span className="eyebrow">Perceber também é se conhecer</span><h2>Seu corpo comunica mudanças todos os dias.</h2><p>O Ciclo MOB reúne suas observações em um histórico pessoal para você acompanhar seus ritmos com presença, continuidade e mais consciência corporal.</p></div><div className="problemGrid"><article><span>01</span><h3>Percepções que se perdem</h3><p>Sem um lugar próprio para registrar, detalhes importantes do cotidiano acabam esquecidos.</p></article><article><span>02</span><h3>Mudanças sem contexto</h3><p>Quando os dias ficam isolados, é mais difícil reconhecer sequências e compreender o próprio ritmo.</p></article><article><span>03</span><h3>Pouco tempo para si</h3><p>Uma rotina simples de observação cria um momento de atenção e cuidado com você.</p></article></div></section>
      <section className="featureSection"><div className="featureImage"><img src="/ciclo-mob-v38-ciclo.png" alt="Tela Meu ciclo da nova versão do Ciclo MOB com gráfico de observações"/></div><div className="featureCopy"><span className="eyebrow">Seu ciclo em perspectiva</span><h2>Do registro diário a uma visão mais consciente de você.</h2><div className="featureList"><div><Check/><p><b>Registro diário guiado</b><br/>Anote sensação, aparência, sangramento, pico e aquilo que percebeu no dia.</p></div><div><Check/><p><b>Gráfico MOB</b><br/>Visualize a sequência das observações e reconheça como o ciclo se desenvolve.</p></div><div><Check/><p><b>História por ciclos</b><br/>Revisite ciclos atuais e anteriores sem perder detalhes da sua trajetória.</p></div><div><Check/><p><b>Aprendizado integrado</b><br/>Amplie seu conhecimento sobre observação do corpo e uso responsável do método.</p></div><div><Check/><p><b>Lembretes e compartilhamento</b><br/>Cultive constância e escolha com quem deseja compartilhar seu acompanhamento.</p></div></div></div></section>
      <section className="steps" id="como-funciona"><div className="sectionHead"><span className="eyebrow">Como funciona</span><h2>Um hábito simples de autoconhecimento.</h2></div><div className="stepGrid"><article><span>1</span><h3>Observe</h3><p>Reserve um instante para perceber os sinais e as sensações do seu corpo.</p></article><article><span>2</span><h3>Registre</h3><p>Organize suas observações diárias de forma simples, privada e guiada.</p></article><article><span>3</span><h3>Compreenda</h3><p>Acompanhe a sequência do ciclo e construa uma visão mais consciente da sua história.</p></article></div></section>
      <section className="detailSection"><div><span className="eyebrow light">Conhecimento que acompanha você</span><h2>Um espaço para se escutar com mais atenção.</h2><p>A trilha educativa ajuda a transformar o registro em compreensão, sempre respeitando sua individualidade e os limites de uma ferramenta digital.</p><ul><li><Check/> Conteúdos curtos e progressivos</li><li><Check/> Interface pensada para o uso diário</li><li><Check/> Ciclos organizados cronologicamente</li><li><Check/> Backup e geração de relatório</li><li><Check/> Sem anúncios dentro do aplicativo</li></ul></div><img src="/ciclo-mob-v38-aprender.png" alt="Tela Aprender da nova versão do aplicativo Ciclo MOB"/></section>
      <section className="pricing" id="planos"><div className="sectionHead"><span className="eyebrow">Escolha seu plano</span><h2>Invista no hábito de se conhecer.</h2><p>Todos os planos liberam a experiência completa do Ciclo MOB.</p></div><div className="pricingGrid">
        <article className="priceCard"><span className="planPeriod">MENSAL</span><h3>Plano mensal</h3><p className="price"><small>R$</small> 49,90 <small>/mês</small></p><p className="priceNote">Cobrança mensal de R$ 49,90.</p><ul><li><Check/> Acesso a todos os recursos</li><li><Check/> Registros e ciclos ilimitados</li><li><Check/> Cancele quando quiser</li></ul><a className="button ghost full" href="#captura">Escolher mensal</a></article>
        <article className="priceCard"><span className="planPeriod">SEMESTRAL</span><h3>Plano semestral</h3><p className="price"><small>R$</small> 29,90 <small>/mês</small></p><p className="priceNote">R$ 179,40 cobrados a cada 6 meses.</p><ul><li><Check/> Acesso a todos os recursos</li><li><Check/> Registros e ciclos ilimitados</li><li><Check/> Economia de 40% por mês</li></ul><a className="button ghost full" href="#captura">Escolher semestral</a></article>
        <article className="priceCard featured"><span className="popular">MELHOR ESCOLHA</span><h3>Plano anual</h3><p className="price"><small>R$</small> 9,90 <small>/mês</small></p><p className="priceNote">R$ 118,80 cobrados uma vez por ano.</p><ul><li><Check/> Acesso a todos os recursos</li><li><Check/> Registros e ciclos ilimitados</li><li><Check/> Maior economia e continuidade</li></ul><a className="button primary full" href="#captura">Escolher anual</a></article>
      </div><p className="pricingFootnote">Assinatura segura. Os planos semestral e anual são cobrados integralmente no início de cada período.</p></section>
      <section className="faq"><div className="sectionHead"><span className="eyebrow">Dúvidas frequentes</span><h2>Antes de começar.</h2></div><div className="faqList"><details><summary>O Ciclo MOB substitui uma instrutora?</summary><p>Não. O aplicativo organiza observações e conteúdos de apoio, mas não substitui orientação individual de uma instrutora qualificada ou de um profissional de saúde.</p></details><details><summary>Preciso instalar pela loja de aplicativos?</summary><p>O Ciclo MOB funciona como aplicativo web e pode ser adicionado à tela inicial do celular.</p></details><details><summary>Posso consultar ciclos anteriores?</summary><p>Sim. O histórico mantém os ciclos organizados para consulta posterior.</p></details><details><summary>Meus registros ficam protegidos?</summary><p>O projeto é desenvolvido com foco em privacidade e controle da usuária sobre seus próprios registros.</p></details></div></section>
      <section className="leadSection" id="captura"><div className="leadCard"><div className="leadCopy"><span className="eyebrow light">Seu primeiro passo de autoconhecimento</span><h2>Ainda não é a hora de assinar?</h2><p>Receba gratuitamente o <b>Guia Prático de Observação do Ciclo</b> e comece a perceber seu corpo com mais atenção e constância.</p><ul><li><Check/> O que observar diariamente</li><li><Check/> Como criar um hábito de percepção</li><li><Check/> Como organizar suas descobertas</li></ul></div><div className="formBox"><LeadForm/></div></div></section>
      <footer><a className="brand" href="#inicio"><span className="brandMark"><img src="/ciclo-mob-logo-oficial.png" alt=""/></span> Ciclo MOB</a><p>Observe. Conheça. Cuide.</p><p className="footerSignature">Ciclo MOB por Cuidados da Mulher</p><p className="legal">O Ciclo MOB é uma ferramenta de organização e educação. Não realiza diagnóstico, não determina fertilidade e não substitui aconselhamento médico ou orientação individual de uma instrutora. © 2026 Ciclo MOB.</p></footer>
    </main>
  );
}
